Repository ARMmbed/mbed-os-example-tls, pull requests merged in 2018-10, with the labels that each got.

#109 tls-client: Check certificate verification flags to exclude time failures
  tls-client/HelloHttpsClient.cpp
Labels: enhancement, mbed TLS team, ready for merge

#204 Updating mbed-os to mbed-os-5.10.1
  authcrypt/mbed-os.lib
  benchmark/mbed-os.lib
  hashing/mbed-os.lib
  tls-client/mbed-os.lib
Labels: ready for merge

#194 Refactor benchmark to mitigate memory problems
  benchmark/main.cpp
  benchmark/mbed_app.json
  benchmark/mbedtls_config.h
  tests/benchmark.log
Labels: enhancement, ready for merge, runCI

#199 Change mbedtls_platform_context parameter to NULL
  authcrypt/authcrypt.cpp
  authcrypt/authcrypt.h
  authcrypt/main.cpp
  benchmark/main.cpp
  hashing/main.cpp
  tls-client/HelloHttpsClient.cpp
  tls-client/HelloHttpsClient.h
  tls-client/main.cpp
Labels: enhancement, ready for merge
